-- Generated by scripts/generate-practical-seed.mjs. Do not edit manually.

BEGIN;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.exams WHERE slug = 'jeongchogi') THEN
    RAISE EXCEPTION 'required exam "jeongchogi" does not exist';
  END IF;
END;
$$;

-- 2025년 3회 정보처리기사 실기

-- 20 questions

INSERT INTO public.questions (id, exam_id, exam_type, year, round, subject, number, content, explanation, reviewed, published)
SELECT
  extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-001$q$), id, 'practical', 2025, 3, $q$실기$q$, 1,
  $q$UML 다이어그램에 대한 다음 설명에서 괄호에 공통으로 들어갈 알맞은 용어를 쓰시오.
(5점)
( ) 다이어그램
( )은(는) UML 정적 모델링의 하나로, 관련있는 객체들을 하나로 묶어 상위 개념으로 추상화한 것이
다. 위의 그림과 같이 유스케이스나 클래스 등의 요소들을 그룹화하여 의존 관계를 표현하며, 대규모 시
스템에서 주요 요소 간의 종속성을 파악하는 데 사용한다. 시스템의 구조를 간략하게 표현할 수 있고 의
존 관계를 명확하게 파악할 수 있어, 불필요한 의존 관계를 제거하거나 간략화함으로써 시스템의 복잡도
를 낮추는 곳에도 사용할 수 있다.$q$, NULL, FALSE, TRUE
FROM public.exams WHERE slug = 'jeongchogi'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-001:blank:1$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-001$q$), 1, ARRAY[$q$패키지$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.questions (id, exam_id, exam_type, year, round, subject, number, content, explanation, reviewed, published)
SELECT
  extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-002$q$), id, 'practical', 2025, 3, $q$실기$q$, 2,
  $q$다음 설명에 해당하는 UNIX 명령어를 <보기>에서 찾아 쓰시오. (5점)
• ( ① ) : 현재 작업중인 디렉터리 경로를 화면에 표시한다.
• ( ② ) : 현재 디렉터리의 파일 목록을 표시한다.
• ( ③ ) : 디렉터리의 위치를 변경한다.
• ( ④ ) : 파일을 복사한다.
<보기>
• ls • fork • ps • cp
• cat • pwd • chmod • cd$q$, NULL, FALSE, TRUE
FROM public.exams WHERE slug = 'jeongchogi'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-002:blank:1$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-002$q$), 1, ARRAY[$q$pwd$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-002:blank:2$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-002$q$), 2, ARRAY[$q$ls$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-002:blank:3$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-002$q$), 3, ARRAY[$q$cd$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-002:blank:4$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-002$q$), 4, ARRAY[$q$cp$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.questions (id, exam_id, exam_type, year, round, subject, number, content, explanation, reviewed, published)
SELECT
  extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-003$q$), id, 'practical', 2025, 3, $q$실기$q$, 3,
  $q$화이트박스 테스트의 검증 기준에 대한 다음 설명에 해당하는 용어를 <보기>에서 찾아
쓰시오. (5점)
테스트 케이스를 소스 코드의 조건문에 포함된 개별 조건식의 결과가 True인 경우와 False인 경우가 한
번 이상 수행되도록 설계한다.
<보기>
• 문장 커버리지 • 분기 커버리지 • 조건 커버리지 • 분기/조건 커버리지$q$, NULL, FALSE, TRUE
FROM public.exams WHERE slug = 'jeongchogi'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-003:blank:1$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-003$q$), 1, ARRAY[$q$조건 커버리지$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.questions (id, exam_id, exam_type, year, round, subject, number, content, explanation, reviewed, published)
SELECT
  extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-004$q$), id, 'practical', 2025, 3, $q$실기$q$, 4,
  $q$다음 설명에서 괄호(①~⑤)에 들어갈 알맞은 용어를 <보기>에서 찾아 기호(㉠~㉧)로
쓰시오. (5점)
• ( ① ) 코드는 데이터 전송 시 오류를 검출하고 수정하는 코드로, 데이터 전송 과정에서 발생한 오류
를 검출해 재전송 요구 없이 수신측에서 스스로 수정하는 ( ② ) 방식에 속한다.
• 이에 반해 오류 발생 시 송신측에 재전송을 요구하는 방식은 ( ③ )이며, 대표적인 종류에는 ( ④ )
검사와 ( ⑤ ) 검사가 있다.
• ( ① ) 코드 : 전송 데이터에 n비트의 검사 비트를 추가해 오류를 검출하고, 수정한다.
• ( ④ ) 검사 : 전송 데이터의 한 블록 끝에 1비트의 검사 비트 추가하여 오류를 검출한다.
• ( ⑤ ) 검사 : 송신측과 수신측이 동일한 특정 다항식을 사용하여 오류를 검출한다.
<보기>
㉠ CRC ㉡ FEC ㉢ BEC ㉣ NAK
㉤ Parity ㉥ MD5 ㉦ BCD ㉧ Hamming$q$, NULL, FALSE, TRUE
FROM public.exams WHERE slug = 'jeongchogi'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-004:blank:1$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-004$q$), 1, ARRAY[$q$㉧$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-004:blank:2$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-004$q$), 2, ARRAY[$q$㉡$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-004:blank:3$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-004$q$), 3, ARRAY[$q$㉢$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-004:blank:4$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-004$q$), 4, ARRAY[$q$㉤$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-004:blank:5$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-004$q$), 5, ARRAY[$q$㉠$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.questions (id, exam_id, exam_type, year, round, subject, number, content, explanation, reviewed, published)
SELECT
  extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-005$q$), id, 'practical', 2025, 3, $q$실기$q$, 5,
  $q$다음 C 언어로 구현된 프로그램을 분석하여 그 실행 결과를 쓰시오. (단, 출력문의 출력
서식을 준수하시오.) (5점)
#include <stdio.h>
struct Test {
int i;
const char *g;
};
int main( ) {
struct Test test[ ] = {{1, "AB"}, {2, "DC"}, {3, "EB"}};
struct Test *p = &test[1];
printf("%s", p->g + (p->i - 1));
return 0;
}$q$, $q$#include <stdio.h>
struct Test { // 구조체 Test를 정의합니다.
int i; // 정수형 변수 i를 선언합니다.
const char *g; // 문자형 포인터 상수 g를 선언합니다.
struct Test
int i(4Byte) char *g(8Byte)
정수를 저장할 멤버 문자열이 저장된 주소를 저장할 멤버
};
int main( ) {
❶ struct Test test[ ] = {{1, "AB"}, {2, "DC"}, {3, "EB"}};
❷ struct Test *p = &test[1];
❸ printf("%s", p->g + (p->i - 1));
❹ return 0;
}
모든 C 프로그램은 반드시 main( ) 메소드에서 시작한다.
❶ 구조체 Test 자료형으로 3개짜리 배열 test를 선언하고 초기화한다. 배열을 선언할 때 배열의 크기를 지정
하지 않으면 초기값의 개수로 배열의 요소가 만들어진다.
메모리
주소
0000
ㆍㆍㆍ test[0] test[1] test[2]
1000 1004 1008 1012 1016 1020 1024 1028 1032 1036 1040 ㆍㆍㆍ
1000 i *g i *g i *g
1 2000 2 2004 3 2008
ㆍㆍㆍ
2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 ㆍㆍㆍ
2000
A B ‘\0’ D C ‘\0’ E B ‘\0’
ㆍㆍㆍ
9999
❷ Test 구조체를 가리키는 포인터 변수 p를 선언하고, test[1]의 주소를 저장한다. p는 1016번지 이후의
12Byte를 의미한다. (이후 그림에서 지정한 주소는 임의로 정한 것이며, 이해를 돕기 위해 10진수로 표현했
다.)
메모리
주소
0000 p 1016
ㆍㆍㆍ test[0] test[1] test[2]
1000 1004 1008 1012 1016 1020 1024 1028 1032 1036 1040 ㆍㆍㆍ
1000 i *g i *g i *g
1 2000 2 2004 3 2008
ㆍㆍㆍ
2000 2001 2002 2003 2004 2005 2006 2007 2008 2009 2010 ㆍㆍㆍ
2000
A B ‘\0’ D C ‘\0’ E B ‘\0’
ㆍㆍㆍ
9999
❸ p가 가리키는 곳의 g가 가리키는 곳의 주소에서 1만큼 증가한 곳의 값을 문자열로 출력한다. 문자열의 출력
은 문자열의 시작 위치부터 문자열의 끝을 의미하는 널 문자(‘\0’) 전까지를 출력한다.
p->g + (p->i – 1)
①
②
③
ㆍ① p->i : p가 가리키는 곳의 i 값은 2다.
ㆍ② ① - 1 → 2 - 1 : 1
ㆍ③ p->g + ② → p->g + 1 : p가 가리키는 곳의 g가 가리키는 곳의 주소인 2004에서 1만큼 증가한 곳인
2005 번지의 값은 “C”다.
결과 C
❹ main( ) 함수에서의 ‘return 0’은 프로그램의 종료를 의미한다.$q$, FALSE, TRUE
FROM public.exams WHERE slug = 'jeongchogi'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-005:blank:1$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-005$q$), 1, ARRAY[$q$C$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.questions (id, exam_id, exam_type, year, round, subject, number, content, explanation, reviewed, published)
SELECT
  extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-006$q$), id, 'practical', 2025, 3, $q$실기$q$, 6,
  $q$다음 Java로 구현된 프로그램을 분석하여 그 실행 결과를 쓰시오. (단, 출력문의 출력
서식을 준수하시오.) (5점)
enum Tri {
A("A"), B("AB"), C("ABC");
private String code;
Tri(String code) {
this.code = code;
}
public String code( ) {
return code;
}
}
public class Main {
public static void main(String[] args) {
Tri t = Tri.values( )[Tri.A.name( ).length( )];
System.out.print(t.code( ));
}
}$q$, $q$enum Tri { // 열거형 Tri 클래스를 정의한다.
① A("A"), B("AB"), C("ABC"); // 열거형 Tri 클래스의 객체 상수 A, B, C를 정의한다.
private String code; // 문자열 변수 code를 객체 상수의 속성으로 정의한다.
② Tri(String code) { // 생성자로, 열거형 상수가 정의될 때 자동으로 호출된다.
③ this.code = code;
}
❸ public String code( ) { // 메소드 code를 객체 상수의 메소드로 정의한다.
❹ return code; // 해당 객체 상수의 속성 code를 반환한다.
}
}
public class Main {
public static void main(String[] args) {
❶ Tri t = Tri.values( )[Tri.A.name( ).length( )];
❷❺ System.out.print(t.code( ));
}
}
모든 Java 프로그램은 main( ) 메소드에서 시작하는데, main( ) 메소드가 시작되기 전 다음과 같이 Tri 열거형
클래스의 객체 상수 초기화 과정이 수행된다.
① 열거형(enum) 객체 상수 A를 선언하면서 “A”를 인수로 생성자를 호출한다. 객체 상수가 정의될 때 해당 객
체가 문자열 변수 code와 문자열을 반환하는 code( ) 메소드도 함께 정의된다.
② 열거형 Tri의 생성자 Tri( )의 시작점이다. ①번에서 전달한 “A”를 code가 받는다.
③ code에 “A”를 저장한다. 즉 객체 상수 A의 code에 “A”가 저장된다.
※ 위와 같은 과정으로 객체 상수 B, C의 초기화도 수행되며, 수행된 결과는 다음과 같다. 열거형 상수는 내부적
으로 선언 순서에 따라 순서가 부여되며, 이 순서는 배열에서 인덱스로 사용된다.
Tri[0] Tri[1] Tri[2]
Tri.A Tri.B Tri.C
code code( ) code code( ) code code( )
“A” “AB” “ABC”
모든 Java 프로그램은 반드시 main( ) 메소드에서 시작한다.
❶ Tri 객체 변수 t에 Tri.values( )[1], 즉 Tri.B를 저장한다.
Tri.values( )[Tri.A.name( ).length( )];
①
②
③
ㆍ① Tri.A.name( ) : Tri의 상수 A의 이름을 문자열 “A” 형태로 반환함
※ name( ) : 열거형 상수의 이름을 문자열로 반환함
ㆍ② ①.length( ) → “A”.length( ) : 문자열 “A”의 길이인 1을 반환함
※ length( ) : 문자열의 길이를 반환함
ㆍ③ Tri.values( )[②] → Tri.values( )[1] : 배열로 변환된 Tri의 상수 중 인덱스가 1인 요소, 즉 Tri.B를
반환함
※ values( ) : 열거형 상수를 배열의 형태로 변환함
❷ t, 즉 Tri.B의 code( ) 메소드를 호출한 후 돌려받은 값을 출력한다. ❸번으로 이동한다.
❸ 문자열을 반환하는 code( ) 메소드의 시작점이다. ❷번에서 Tri.B의 code( ) 메소드가 호출되었으므로 현재
code는 “AB”이다.
❹ code의 값 “AB”를 메소드를 호출했던 ❺번으로 반환한다.
❺ ❹번으로부터 반환받은 값 AB를 출력한다.
결과 AB$q$, FALSE, TRUE
FROM public.exams WHERE slug = 'jeongchogi'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-006:blank:1$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-006$q$), 1, ARRAY[$q$AB$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.questions (id, exam_id, exam_type, year, round, subject, number, content, explanation, reviewed, published)
SELECT
  extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-007$q$), id, 'practical', 2025, 3, $q$실기$q$, 7,
  $q$<A> 테이블과 <B> 테이블을 참고하여 <SQL문>의 실행 결과를 쓰시오. (5점)
<A> <B>
NAME RULE
Smith S%
Allen %T%
Scott
<SQL문>
SELECT COUNT(*) CNT FROM A CROSS JOIN B WHERE A.NAME LIKE B.RULE;$q$, $q$SELECT COUNT(*) CNT
FROM A CROSS JOIN B
WHERE A.NAME LIKE B.RULE;
질의문은 각 절을 분리하여 이해하면 쉽습니다.
ㆍSELECT COUNT(*) CNT : 튜플의 개수를 표시하되, 필드명은 ‘CNT’로 표시합니다.
※ ‘SELECT COUNT(*) AS CNT’에서 AS가 생략된 형태입니다.
ㆍFROM A CROSS JOIN B : <A>와 <B>를 교차 조인(CROSS JOIN)한 결과를 대상으로 검색합니다.
A.NAME B.RULE
Smith S%
Smith %T%
Allen S%
Allen %T%
Scott S%
Scott %T%
ㆍWHERE A.NAME LIKE B.RULE : <A> 테이블의 ‘NAME’ 필드 값이 <B> 테이블의 ‘RULE’ 필드에 저장된 문
자열 패턴과 일치하는 튜플만을 대상으로 합니다.
※ <B> 테이블의 ‘RULE’ 필드에 저장된 값은 ‘S%’와 ‘%T%’와 같이 문자 패턴인 ‘%’ 기호가 포함되어 있으므
로, 조건문의 LIKE 연산자와 결합되면 다음과 같이 적용됩니다.
- A.NAME LIKE S% : ‘A.NAME’이 “S”로 시작하는 레코드를 검색
NAME RULE
Smith S%
Smith %T%
Allen S%
Allen %T%
Scott S%
Scott %T%
- A.NAME LIKE %T% : ‘A.NAME’이 “T”를 포함하는 레코드를 검색
NAME RULE
Smith S%
Smith %T%
Allen S%
Allen %T%
Scott S%
Scott %T%
※ CROSS JOIN된 결과에서 조건을 만족하는 튜플은 다음과 같습니다. 그러므로 검색된 튜플의 개수는 4입니다.
NAME RULE
Smith S%
Smith %T%
Scott S%
Scott %T%$q$, FALSE, TRUE
FROM public.exams WHERE slug = 'jeongchogi'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-007:blank:1$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-007$q$), 1, ARRAY[$q$4$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.questions (id, exam_id, exam_type, year, round, subject, number, content, explanation, reviewed, published)
SELECT
  extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-008$q$), id, 'practical', 2025, 3, $q$실기$q$, 8,
  $q$다음 설명에 해당하는 용어를 <보기>에서 찾아 쓰시오. (5점)
• 인터넷 애플리케이션에서 사용자 인증에 사용되는 표준 인증 방법으로, 공개 API(OpenAPI)로 구현되었
다.
• 인터넷 사용자가 웹사이트나 애플리케이션에 비밀번호를 제공하지 않고 자신에게 접근 권한을 부여하여
사용할 수 있다.
• 2010년 ETF에서 1.0이 공식 표준안으로 발표되었다.
<보기>
• OpenID • IDEA • OAuth • SSPI
• SASL • PEAP • OIDC • JAAS$q$, NULL, FALSE, TRUE
FROM public.exams WHERE slug = 'jeongchogi'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-008:blank:1$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-008$q$), 1, ARRAY[$q$oAuth$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.questions (id, exam_id, exam_type, year, round, subject, number, content, explanation, reviewed, published)
SELECT
  extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-009$q$), id, 'practical', 2025, 3, $q$실기$q$, 9,
  $q$다음 설명에 해당하는 알맞은 용어를 영문 약어로 쓰시오. (5점)
• 사용자가 패스워드를 요청할 때마다 암호 알고리즘과 해시 함수를 이용하여 새로운 일회용 패스워드를
생성하며, 한 번 사용된 패스워드는 폐기되어 재사용할 수 없다.
• 주로 은행 및 금융 거래 시 사용자 본인 인증을 강화하기 위해 널리 사용된다.$q$, NULL, FALSE, TRUE
FROM public.exams WHERE slug = 'jeongchogi'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-009:blank:1$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-009$q$), 1, ARRAY[$q$OTP$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.questions (id, exam_id, exam_type, year, round, subject, number, content, explanation, reviewed, published)
SELECT
  extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-010$q$), id, 'practical', 2025, 3, $q$실기$q$, 10,
  $q$다음 Java로 구현된 프로그램을 분석하여 괄호에 들어갈 알맞은 코드를 쓰시오. (5점)
interface Cals {
public void get(int v);
}
class Test ( ) Cals {
public void get(int v) {
System.out.print(v*v);
}
}
public class Main {
public static void main(String[] args) {
Cals a = new Test();
a.get(10);
}
}$q$, $q$Ⓐ interface Cals {
Ⓑ public void get(int v);
}
Ⓒ class Test implements Cals {
Ⓓ ❸ public void get(int v) {
❹ System.out.print(v*v);
}
}
public class Main {
public static void main(String[] args) {
❶ Cals a = new Test();
❷ a.get(10);
} ❺
}
Ⓐ 인터페이스 Cals를 선언한다.
Ⓑ 반환값이 없는 get( )을 선언한다. 인터페이스에 선언된 메소드는 선언만 있고 내부에 실행 코드가 없는 추
상 메소드이므로, 이후 상속 관계가 설정된 자식 클래스에서 재정의한 후 사용한다.
Ⓒ Cals 인터페이스를 상속받는 클래스 Test를 정의한다.
Ⓓ 반환값이 없는 get( )을 정의한다. get( ) 메소드는 Ⓑ에서 선언된 추상 메소드(Ⓑ)를 재정의하는 것이다.
※ 추상 메소드는 부모 클래스가 자식 클래스에게 주는 의무와 같습니다. 부모 클래스와 상속 관계에 있다면 반드시 부모 클래
스의 추상 메소드를 재정의해야 합니다. 그렇지 않으면 프로그램에 오류가 발생합니다.
모든 Java 프로그램은 반드시 main( ) 메소드에서 시작한다.
❶ Test 클래스의 생성자를 이용하여 Cals의 객체 변수 a를 선언한다. 부모 클래스의 객체 변수를 선언하면서
자식 클래스의 생성자를 사용하면 형 변환이 발생한다. 이렇게 형 변환이 발생했을 때 부모 클래스와 자식
클래스에 동일한 속성이나 메소드가 있으면 부모클래스의 속성이나 메소드가 자식 클래스의 속성이나 메소
드로 재정의된다.
❷ 10을 인수로 하여 a의 get( ) 메소드를 호출한다. ❸번으로 이동한다.
※ get( ) 메소드는 a 객체의 자료형이 Cals이므로 Cals 클래스의 get( )이라고 생각할 수 있지만 ❶번에서 클래스
형 변환이 발생하였고, get( ) 메소드가 자식 클래스에서 재정의되었으므로 Test 클래스의 get( ) 메소드가 수행
됩니다.
❸ 반환값이 없는 get( ) 메소드의 시작점이다. ❷번에서 전달받은 10을 v가 받는다.
❹ v*v의 결과값인 100을 출력한 후 메소드가 종료되면, 호출했던 ❷번의 다음 줄인 ❺번으로 이동하여 프로그
램을 종료한다.
결과 100$q$, FALSE, TRUE
FROM public.exams WHERE slug = 'jeongchogi'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-010:blank:1$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-010$q$), 1, ARRAY[$q$implements$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.questions (id, exam_id, exam_type, year, round, subject, number, content, explanation, reviewed, published)
SELECT
  extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-011$q$), id, 'practical', 2025, 3, $q$실기$q$, 11,
  $q$다음 Python으로 구현된 프로그램을 분석하여 출력값(①~⑧)에 들어갈 알맞은 값을 쓰
시오. (5점)
data = [
[3, 5, 2, 4, 1],
[4, 5, 1],
[4, 4, 1, 5, 4],
[4, 5]
]
result = { }
for index, lis in enumerate(data):
list_sum = sum(lis)
list_len = len(lis)
result[index] = (list_sum, list_len)
print(result)
<출력값>
{0: (①, ②), 1: (③, ④), 2: (⑤, ⑥), 3: (⑦, ⑧)}$q$, $q$❶ data = [
[3, 5, 2, 4, 1],
[4, 5, 1],
[4, 4, 1, 5, 4],
[4, 5]
]
❷ result = { }
❸ for index, lis in enumerate(data):
❹ list_sum = sum(lis)
❺ list_len = len(lis)
❻ result[index] = (list_sum, list_len)
❼ print(result)
❶ 리스트 안에 리스트가 저장되는 다차원 리스트 data를 선언하고, 다음과 같이 초기화한다.
리스트 data
[0] [1] [2] [3] [4]
data[0] 3 5 2 4 1
data[1] 4 5 1
data[2] 4 4 1 5 4
data[3] 4 5
❷ 딕셔너리 result를 선언한다.
❸ 리스트 data의 요소 수만큼 ❹~❻번 문장을 반복 수행한다. 리스트 data는 4개의 요소를 가지므로 각 요소
의 ‘인덱스’와 ‘요소값’을 index와 lis에 할당하면서 ❹~❻번 문장을 4회 수행한다.
ㆍenumerate( ) : 반복 가능한 객체를 대상으로 해당 객체의 요소를 ‘인덱스, 요소값’의 형태로, 인덱스와 요
소를 묶어서 반환함
❹ list_sum에 계산된 lis의 모든 요소의 합을 저장한다.
ㆍsum( ) : 리스트의 모든 요소의 합을 계산하여 반환함
❺ list_len에 계산된 lis 요소의 개수를 저장한다.
ㆍlen( ) : 리스트 요소의 개수를 반환함
❻ 딕셔너리 result의 index 위치에 (list_sum, list_len)을 값으로 저장한다.
반복문 실행에 따른 변수들의 변화는 다음과 같다.
index lis list_sum list_len result
[0]
0 3 5 2 4 1 15 5
15 5
[0] [1]
1 4 5 1 10 3
15 5 10 3
[0] [1] [2]
2 4 4 1 5 4 18 5
15 5 10 3 18 5
[0] [1] [2] [3]
3 4 5 9 2
15 5 10 3 18 5 9 2
❼ 딕셔너리 result를 출력한다.
결과 {0: (15, 5), 1: (10, 3), 2: (18, 5), 3: (9, 2)}$q$, FALSE, TRUE
FROM public.exams WHERE slug = 'jeongchogi'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-011:blank:1$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-011$q$), 1, ARRAY[$q$15$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-011:blank:2$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-011$q$), 2, ARRAY[$q$5$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-011:blank:3$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-011$q$), 3, ARRAY[$q$10$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-011:blank:4$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-011$q$), 4, ARRAY[$q$3$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-011:blank:5$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-011$q$), 5, ARRAY[$q$18$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-011:blank:6$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-011$q$), 6, ARRAY[$q$5$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-011:blank:7$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-011$q$), 7, ARRAY[$q$9$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-011:blank:8$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-011$q$), 8, ARRAY[$q$2$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.questions (id, exam_id, exam_type, year, round, subject, number, content, explanation, reviewed, published)
SELECT
  extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-012$q$), id, 'practical', 2025, 3, $q$실기$q$, 12,
  $q$다음 <R>과 <S> 테이블에 대해 ‘R ÷ S’를 실행했을 때 출력되는 결과를 테이블로 작성
하시오. (5점)
<R> <S>
A B B
a1 b1 b1
a2 b2 b3
a1 b3$q$, $q$‘R ÷ S’에서 ÷는 R의 속성 중 S의 속성값을 모두 가진 튜플에서 S가 가진 속성을 제외한 속성만을 구하는
연산입니다.
① R의 속성에서 S의 속성값을 모두 가진 튜플을 추출합니다.
<R> <S> <R>
A B B A B
a1 b1 b1 a1 b1
a2 b2 b3 a1 b3
a1 b3 ➡
② ①의 결과에서 S가 가진 속성을 제외한 속성만 추출합니다. 결과를 만족하는 <R>의 속성은 ‘A’이며, ‘A’
속성의 고유한 값은 a1입니다.
<R> <R>
A A
a1 a1
a1 ➡$q$, FALSE, TRUE
FROM public.exams WHERE slug = 'jeongchogi'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-012:blank:1$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-012$q$), 1, ARRAY[$q$A a1$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.questions (id, exam_id, exam_type, year, round, subject, number, content, explanation, reviewed, published)
SELECT
  extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-013$q$), id, 'practical', 2025, 3, $q$실기$q$, 13,
  $q$접근 통제(Access Control)에 대한 다음 설명에서 괄호(①~③)에 들어갈 알맞은 용어를
<보기>에서 찾아 쓰시오. (5점)
• 주체와 객체의 등급을 비교하여 접근 권한을 부여하는 방식이다.
• 시스템이 접근통제 권한을 지정한다.
( ① )
• 데이터베이스 객체별로 보안 등급을 부여할 수 있다.
• 사용자별로 인가 등급을 부여할 수 있다.
• 사용자의 역할에 따라 접근 권한을 부여하는 방식이다.
• 중앙관리자가 접근통제 권한을 지정한다.
( ② )
• 임의 접근통제와 강제 접근통제의 단점을 보완하였다.
• 다중 프로그래밍 환경에 최적화된 방식이다.
• 데이터에 접근하는 사용자의 신원에 따라 접근 권한을 부여하는 방식이다.
• 데이터 소유자가 접근통제 권한을 지정하고 제어한다.
( ③ )
• 객체를 생성한 사용자가 생성된 객체에 대한 모든 권한을 부여받고, 부여된 권한을 다른 사
용자에게 허가할 수도 있다.
<보기>
• DAC(Discretionary Access Control)
• MAC(Mandatory Access Control)
• RBAC(Role Based Access Control)$q$, NULL, FALSE, TRUE
FROM public.exams WHERE slug = 'jeongchogi'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-013:blank:1$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-013$q$), 1, ARRAY[$q$MAC$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-013:blank:2$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-013$q$), 2, ARRAY[$q$RBAC$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-013:blank:3$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-013$q$), 3, ARRAY[$q$DAC$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.questions (id, exam_id, exam_type, year, round, subject, number, content, explanation, reviewed, published)
SELECT
  extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-014$q$), id, 'practical', 2025, 3, $q$실기$q$, 14,
  $q$다음 테스트 케이스를 참조하여 괄호(①~③)에 들어갈 테스트 케이스의 구성 요소를
<보기>에서 찾아 쓰시오. (5점)
식별자_ID 테스트 항목 ( ① ) ( ② ) ( ③ )
아이디(test_a01)
LS_W10_35 로그인 기능 사용자 초기 화면 로그인 성공
비밀번호(203a!d5%ffa1)
아이디(test_a01) 로그인 실패(1)
LS_W10_36 로그인 기능 사용자 초기 화면
비밀번호(1234) - 비밀번호 비일치
아이디(“ ”) 로그인 실패(2)
LS_W10_37 로그인 기능 사용자 초기 화면
비밀번호(“ ”) - 미입력
<보기>
• 요구 절차 • 의존성 여부 • 테스트 데이터 • 테스트 조건
• 하드웨어 환경 • 예상 결과 • 소프트웨어 환경 • 성공/실패 기준$q$, NULL, FALSE, TRUE
FROM public.exams WHERE slug = 'jeongchogi'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-014:blank:1$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-014$q$), 1, ARRAY[$q$테스트 조건$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-014:blank:2$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-014$q$), 2, ARRAY[$q$테스트 데이터$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-014:blank:3$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-014$q$), 3, ARRAY[$q$예상 결과$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.questions (id, exam_id, exam_type, year, round, subject, number, content, explanation, reviewed, published)
SELECT
  extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-015$q$), id, 'practical', 2025, 3, $q$실기$q$, 15,
  $q$릴레이션을 구성하는 용어들에 대한 다음 설명에서 괄호(①~③)에 들어갈 알맞은 답을
<보기>에서 찾아 쓰시오. (5점)
• ( ① ) : 릴레이션을 구성하는 각각의 행을 의미하며, 파일 구조에서는 레코드에 해당함
• ( ② ) : 데이터 개체를 구성하고 있는 속성들에 데이터 타입이 정의되어 구체적인 데이터 값을 가진
것으로, 실제 값을 가진 튜플을 의미함
• ( ③ ) : 튜플의 개수를 의미함
<보기>
• 도메인 • 차수 • 속성 • 튜플
• 디그리 • 카디널리티 • 릴레이션 스키마 • 릴레이션 인스턴스$q$, NULL, FALSE, TRUE
FROM public.exams WHERE slug = 'jeongchogi'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-015:blank:1$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-015$q$), 1, ARRAY[$q$튜플$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-015:blank:2$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-015$q$), 2, ARRAY[$q$릴레이션 인스턴스$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-015:blank:3$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-015$q$), 3, ARRAY[$q$카디널리티$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.questions (id, exam_id, exam_type, year, round, subject, number, content, explanation, reviewed, published)
SELECT
  extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-016$q$), id, 'practical', 2025, 3, $q$실기$q$, 16,
  $q$다음 C 언어로 구현된 프로그램을 분석하여 그 실행 결과를 쓰시오. (단, 출력문의 출력
서식을 준수하시오.) (5점)
#include <stdio.h>
int main(void) {
char str[ ] = "REPUBLICOFKOREA";
int a = 0;
while (str[a] != '\0')
++a;
putchar(str[a-2]);
return 0;
}$q$, $q$#include <stdio.h>
int main(void) {
❶ char str[ ] = "REPUBLICOFKOREA";
❷ int a = 0;
❸ while (str[a] != '\0')
❹ ++a;
❺ putchar(str[a-2]);
❻ return 0;
}
❶ 문자형 배열 str을 선언하고 초기화한다. 배열의 크기를 생략하면, 초기값으로 지정한 개수만큼 배열이 선언
되는데, 문자열의 경우 문자열의 끝을 의미하는 널 문자(‘\0’)가 추가되어 16개의 요소를 갖는 배열로 선언된
다.
[0] [1] [2] [3] [4] [5] [6] [7] [8] [9] [10] [11] [12] [13] [14] [15]
str R E P U B L I C O F K O R E A \0
❷ 정수형 변수 a를 선언하고, 0으로 초기화한다.
❸ str[a]가 ‘\0’(널 문자)가 아닌 동안 ❹번을 반복 수행한다.
❹ ‘a = a + 1;’과 동일하다. a의 값을 1씩 증가시킨다.
반복문 실행에 따른 변수들의 변화는 다음과 같다.
a str[a] str[a] != ‘\0’
0 R No
1 E No
2 P No
3 U No
4 B No
5 L No
6 I No
7 C No
8 O No
9 F No
10 K No
11 O No
12 R No
13 E No
14 A No
15 \0 YES
❻ str[a-2], 즉 str[13]의 값 E를 출력한다.
결과 E
❼ main( ) 함수에서의 ‘return 0;’은 프로그램의 종료를 의미한다.$q$, FALSE, TRUE
FROM public.exams WHERE slug = 'jeongchogi'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-016:blank:1$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-016$q$), 1, ARRAY[$q$E$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.questions (id, exam_id, exam_type, year, round, subject, number, content, explanation, reviewed, published)
SELECT
  extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-017$q$), id, 'practical', 2025, 3, $q$실기$q$, 17,
  $q$다음 C 언어로 구현된 프로그램을 분석하여 그 실행 결과를 쓰시오. (단, 출력문의 출력
서식을 준수하시오.) (5점)
#include <stdio.h>
int main( ) {
int x = 7, y = 4, z;
z = y % 3 < 3 ? 2 : 1;
z = z & z >> 1;
z = x > 5 && z <= 3 ? z * x : z / x;
printf("%d", z);
return 0;
}$q$, $q$#include <stdio.h>
int main( ) {
❶ int x = 7, y = 4, z;
❷ z = y % 3 < 3 ? 2 : 1;
❸ z = z & z >> 1;
❹ z = x > 5 && z <= 3 ? z * x : z / x;
❺ printf("%d", z);
❻ return 0;
}
❶ 정수형 변수 x, y, z를 선언하고, x는 7로, y는 4로 초기화한다.
❷ y를 3으로 나눈 나머지가 3보다 작으면 z에 2를 저장하고, 아니면 1을 저장한다. y의 값 4를 3으로 나눈 나
머지 1은 3보다 작으므로 z에는 2가 저장된다.
❸ ‘z & z >> 1’의 결과 0을 z에 저장한다.
z & z >> 1
①
②
ㆍ① z >> 1 : z의 값 2(0010 )를 오른쪽으로 1비트 이동시킨 1(0001 )을 반환함
2 2
ㆍ② z & ① → z & 1 : z의 값 2(0010 )와 1(0001 )의 논리곱(&) 연산의 결과인 0(0000 )을 반환함
2 2 2
❹ 조건이 참이면 ‘z*x’의 값을 저장하고, 아니면 ‘z/x’의 값을 z에 저장한다. 조건이 참이므로 ‘z*x’의 값 0을 z
에 저장한다.
x > 5 && z <= 3
① ②
③
ㆍ① x > 5 : x의 값 7은 5보다 크므로 참(True)을 반환
ㆍ② z <= 3 : z의 값 0은 3보다 작으므로 참(True)을 반환
ㆍ③ ① && ② → True && True : 두 항목 모두 참(True)이므로 z에는 ‘z*x’의 값 0이 저장됨
❺ z의 값 0을 출력한다.
결과 0
❻ main( ) 함수에서의 ‘return 0;’은 프로그램의 종료를 의미한다.$q$, FALSE, TRUE
FROM public.exams WHERE slug = 'jeongchogi'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-017:blank:1$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-017$q$), 1, ARRAY[$q$0$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.questions (id, exam_id, exam_type, year, round, subject, number, content, explanation, reviewed, published)
SELECT
  extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-018$q$), id, 'practical', 2025, 3, $q$실기$q$, 18,
  $q$다음 Java로 구현된 프로그램을 분석하여 괄호에 들어갈 알맞은 코드를 쓰시오. (5점)
class Rectangle {
int x, y;
Rectangle(int x, int y) {
this.x = x;
this.y = y;
}
int getArea( ) {
return x*y;
}
}
class Square extends Rectangle {
Square(int a) {
( )(a, a);
}
int getSquareArea( ) {
return x*y;
}
}
public class Main {
public static void main(String[] args) {
Square sq = new Square(10);
System.out.println(sq.getSquareArea( ));
}
}$q$, $q$class Rectangle {
int x, y;
❹ Rectangle(int x, int y) {
❺ this.x = x;
❻ this.y = y;
}
int getArea( ) {
return x*y;
}
}
class Square extends Rectangle { // Square를 클래스 정의하고 부모 클래스로 Rectangle을 지정하면
Rectangle에 속한 변수와 메소드를 상속받으므로, Square 클래스
에서는 Rectangle의 변수와 메소드를 사용할 수 있게 된다.
❷ Square(int a) {
❸ super(a, a);
}
❽ int getSquareArea( ) {
❾ return x*y;
}
}
public class Main {
public static void main(String[] args) {
❶ Square sq = new Square(10);
❼❿ System.out.println(sq.getSquareArea( ));
}
}
❶ Square 클래스의 객체 변수 sq를 선언한다. 10을 인수로 하여 Square 클래스의 생성자를 호출한다.
❷ Square 클래스의 생성자인 Square( ) 메소드의 시작점이다. ❷번에서 전달한 10을 a가 받는다.
객체 변수 sq
Square
Square(int a)
a
10
❸ 부모 클래스의 생성자를 호출하며, 인수로 a와 a, 즉 10과 10을 전달한다.
ㆍsuper : 상속한 부모 클래스를 가리키는 예약어
❹ 부모 클래스인 Rectangle 클래스의 생성자 Rectangle( )의 시작점이다. ❸번에서 전달한 10과 10을 x와 y가
받는다.
객체 변수 sq
Square Rectangle
Square(int a) 상속된 공용 변수 Rectangle(int x, int y)
a x y x y
10 10 10
❺ ‘Rectangle.x = x;’와 동일하다. Rectangle.x에 10을 저장한다.
ㆍthis : 현재 실행중인 메소드가 속한 클래스를 가리키는 예약어
❻ Rectangle.y에 10을 저장한다.
Rectangle( ) 생성자가 종료되면 생성자를 호출했던 ❸번으로 돌아간 후 Square( ) 생성자도 종료되므로
Square( ) 생성자를 호출했던 ❶번의 다음 줄인 ❼번으로 이동한다.
객체 변수 sq
Square Rectangle
Square(int a) 상속된 공용 변수 Rectangle(int x, int y)
a x y x y
10 10 10 10 10
❼ sq.getSquareArea( ) 메소드를 호출하여 반환받은 값을 출력한다. sq는 Square 클래스의 객체 변수이므로
Square 클래스의 getSquareArea( ) 메소드를 호출한다. ❽번으로 이동한다.
❽ 정수를 반환하는 getSquareArea( ) 메소드의 시작점이다.
❾ Square 클래스는 부모 클래스인 Rectangle 클래스의 변수를 상속 받았으므로, x*y의 값 100을 함수를 호출
했던 ❿번으로 반환한다.
객체 변수 sq
Square Rectangle
Square(int a) 상속된 공용 변수 Rectangle(int x, int y)
a x y x y
10 10 10 10 10
❿ ❾번으로부터 반환받은 값 100을 출력한다.
결과 100$q$, FALSE, TRUE
FROM public.exams WHERE slug = 'jeongchogi'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-018:blank:1$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-018$q$), 1, ARRAY[$q$super$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.questions (id, exam_id, exam_type, year, round, subject, number, content, explanation, reviewed, published)
SELECT
  extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-019$q$), id, 'practical', 2025, 3, $q$실기$q$, 19,
  $q$다음 C 언어로 구현된 프로그램을 분석하여 그 실행 결과를 쓰시오. (단, 출력문의 출력
서식을 준수하시오.) (5점)
#include <stdio.h>
struct Node {
struct Node* next;
unsigned int x;
};
int main( ) {
struct Node t1 = {0, 5u};
struct Node t2 = {0, 7u};
struct Node t3 = {0, 11u};
t3.next = &t2;
t2.next = &t1;
struct Node* curr = &t3;
int sum = 0;
while (curr) {
sum = sum * 3 + curr->x;
curr = curr->next;
}
sum = (sum ^ 42u) + 100u;
printf("%u\n", sum);
}$q$, $q$#include <stdio.h>
struct Node { // Node 구조체를 정의한다.
struct Node* next; // Node 구조체의 포인터 변수 next를 선언한다.
unsigned int x; // 부호없는 정수형 변수 x를 선언한다.
struct Node
struct Node* next (4Byte) unsigned int x (4Byte)
다음 노드의 주소를 저장할 멤버 데이터를 저장할 멤버
};
int main( ) {
❶ struct Node t1 = {0, 5u};
❷ struct Node t2 = {0, 7u};
❸ struct Node t3 = {0, 11u};
❹ t3.next = &t2;
❺ t2.next = &t1;
❻ struct Node* curr = &t3;
❼ int sum = 0;
❽ while (curr) {
❾ sum = sum * 3 + curr->x;
❿ curr = curr->next;
}
⓫ sum = (sum ^ 42u) + 100u;
⓬ printf("%u\n", sum);
}
❶ Node 자료형 변수 t1을 선언하고, Node의 next에 0을 Node의 x에 부호 없는 정수 5를 저장한다.
. t1이 가리키고 있는 1008 번지는 Node 구조체의 크기만큼 할당된 공간이므로 t1은 1008번지 이후의 8Byte
를 의미한다.
. 이후 그림에서 지정한 주소는 임의로 정한 것이며, 이해를 돕기 위해 10진수로 표현했다.
. 5u에서 ‘u’는 부호 없는 정수형 타입을 의미하는 접미사로 숫자 뒤에 ‘u’나 ‘U’를 붙이면 부호 없는 정수형으
로 처리된다.
. next에 0이 저장되어 있는 것은 어떤 곳도 가리키지 않고 있음을 의미한다.
메모리
주소
0000 t1 1008
ㆍㆍㆍ
8Byte
1000 1004 1008 1012 1016 1020 1024 1028 ㆍㆍㆍ
1000 next x
0 5
ㆍㆍㆍ
9999
❷ Node 자료형 변수 t2를 선언하고, Node의 next에 0을 Node의 x에 7을 저장한다.
메모리
주소
t1 1008
0000
ㆍㆍㆍ
8Byte
t2 1024
1000 1004 1008 1012 1016 1020 1024 1028 ㆍㆍㆍ
1000 next x next x
0 5 0 7
ㆍㆍㆍ
9999
❸ Node 자료형 변수 t3을 선언하고, Node의 next에 0을 Node의 x에 11을 저장한다.
메모리
주소
0000 t1 1008
ㆍㆍㆍ
t2 1024
1000 1004 1008 1012 1016 1020 1024 1028
1000 next x next x
0 5 0 7
ㆍㆍㆍ ㆍㆍㆍ t3 2024
2000 2004 2008 2012 2016 2020 2024 2028
2000 next x
0 11
ㆍㆍㆍ
9999
❹ t3의 next에 t2의 주소를 저장한다. next는 다음 노드의 주소를 가리키는 것이므로, 이제 t3의 다음 노드는
t2이다.
메모리
주소
0000
ㆍㆍㆍ
1000 1004 1008 1012 1016 1020 1024 1028
1000 next x next x
0 5 0 7
ㆍㆍㆍ ㆍㆍㆍ
2000 2004 2008 2012 2016 2020 2024 2028
2000 next x
1024 11
ㆍㆍㆍ
9999
❺ t2의 next에 t1의 주소를 저장한다. 이제 t2의 다음 노드는 t1이므로, 노드의 순서는 ‘t3 → t2 → t1’이 된
다.
메모리
주소
0000
ㆍㆍㆍ
1000 1004 1008 1012 1016 1020 1024 1028
1000 next x next x
0 5 1008 7
ㆍㆍㆍ ㆍㆍㆍ
2000 2004 2008 2012 2016 2020 2024 2028
2000 next x
1024 11
ㆍㆍㆍ
9999
❻ Node 자료형 포인터 변수 curr을 선언하고, t3의 주소를 저장한다.
메모리
주소
0000
ㆍㆍㆍ
1000 1004 1008 1012 1016 1020 1024 1028
1000 next x next x
0 5 1008 7
ㆍㆍㆍ ㆍㆍㆍ curr 2024
2000 2004 2008 2012 2016 2020 2024 2028
2000 next x
1024 11
ㆍㆍㆍ
9999
❼ 정수형 변수 sum을 선언하고, 0으로 초기화한다.
❽ curr이 참인 동안, 즉 0(거짓)이 아닌 동안 ❾, ❿번을 반복 수행한다.
❾ ‘sum * 3 + curr->x’의 값을 sum에 저장한다.
❿ curr이 가리키는 곳의 next를 curr에 저장한다.
반복문 실행에 따른 변수들의 변화는 다음과 같다.
curr->x sum curr
0 2024
11 11 1024
7 40 1008
5 125 0
⓫ ‘(sum ^ 42) + 100’, 즉 sum의 값 125와 42의 비트 XOR(^) 연산의 결과인 87에 100을 더한 값 187을
sum에 저장한다.
01111101 125
^(XOR) 00101010 42
01010111 87
⓬ sum의 값 187을 부호 없는 정수형으로 출력한다.
결과 187$q$, FALSE, TRUE
FROM public.exams WHERE slug = 'jeongchogi'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-019:blank:1$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-019$q$), 1, ARRAY[$q$187$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

INSERT INTO public.questions (id, exam_id, exam_type, year, round, subject, number, content, explanation, reviewed, published)
SELECT
  extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-020$q$), id, 'practical', 2025, 3, $q$실기$q$, 20,
  $q$다음 <A> 테이블을 참조하여 <SQL문>을 실행했을 때 출력되는 결과를 쓰시오. (<A>
테이블에 표시된 ‘NULL’은 값이 없음을 의미한다.) (5점)
<A>
COL1 COL2
2 NULL
3 6
2 3
NULL 3
4 5
<SQL문>
SELECT COUNT(COL2)
FROM A
WHERE COL1 IN (2, 3)
OR COL2 IN (3, 5);$q$, $q$SELECT COUNT(COL2) ‘COL2’의 개수를 표시한다.
FROM A <A> 테이블을 대상으로 검색한다.
WHERE COL1 IN (2, 3) ‘COL1’이 2 또는 3이거나,
OR COL2 IN (3, 5); ‘COL2’가 3 또는 5인 튜플만을 대상으로 한다.
ㆍ질의문의 조건을 만족하는 튜플은 다음과 같습니다.
INDEX COL1 COL2
1 2 NULL
2 3 6
3 2 3
4 NULL 3
5 4 5
ㆍ모든 행이 조건에 맞으므로, ‘COL2’ 속성만 추출하면 다음과 같습니다.
COL2
NULL
6
3
3
5
ㆍCOUNT(COL2)는 ‘COL2’ 필드의 개수를 계산하지만 ‘NULL’ 값은 제외하므로 COUNT(COL2)의 결과는 4입니
다.$q$, FALSE, TRUE
FROM public.exams WHERE slug = 'jeongchogi'
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.practical_answers (id, question_id, blank_number, accepted_answers)
VALUES (extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-020:blank:1$q$), extensions.uuid_generate_v5(extensions.uuid_ns_url(), $q$abubae:practical:jeongchogi-practical-2025-3-020$q$), 1, ARRAY[$q$4$q$]::text[])
ON CONFLICT (question_id, blank_number) DO NOTHING;

COMMIT;
